name: Deploy Pub/Sub
 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create JSON credentials file
      id: create-json-credentials
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "gcloud-service-key.json"
        json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Authenticate to Google Cloud
      run: gcloud auth activate-service-account --key-file=gcloud-service-key.json

    - name: Enable APIs
      run: |
        gcloud services enable pubsub.googleapis.com

    - name: Set working directory
      run: cd tf_create_pubsub

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        working-directory: tf_create_pubsub

    - name: Initialize Terraform
      run: terraform init
      working-directory: tf_create_pubsub

    - name: Validate Terraform
      run: terraform validate
      working-directory: tf_create_pubsub

    - name: Plan Terraform
      run: terraform plan -out=tfplan
      working-directory: tf_create_pubsub
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud-service-key.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: "us-central1"

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
      working-directory: tf_create_pubsub
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud-service-key.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: "us-central1"
